// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SportPlanner.Infrastructure.Data;

#nullable disable

namespace SportPlanner.Infrastructure.Migrations
{
    [DbContext(typeof(SportPlannerDbContext))]
    partial class SportPlannerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SportPlanner.Domain.Entities.AgeGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxAge")
                        .HasColumnType("integer");

                    b.Property<int>("MinAge")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("Sport", "SortOrder");

                    b.HasIndex("Sport", "MinAge", "MaxAge");

                    b.ToTable("age_groups", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111001"),
                            Code = "ALEVIN_FOOTBALL",
                            CreatedAt = new DateTime(2025, 9, 28, 16, 31, 21, 586, DateTimeKind.Utc).AddTicks(8490),
                            CreatedBy = "System",
                            IsActive = true,
                            MaxAge = 10,
                            MinAge = 8,
                            Name = "Alevín",
                            SortOrder = 1,
                            Sport = "Football"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111002"),
                            Code = "BENJAMIN_FOOTBALL",
                            CreatedAt = new DateTime(2025, 9, 28, 16, 31, 21, 586, DateTimeKind.Utc).AddTicks(8498),
                            CreatedBy = "System",
                            IsActive = true,
                            MaxAge = 12,
                            MinAge = 11,
                            Name = "Benjamín",
                            SortOrder = 2,
                            Sport = "Football"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111003"),
                            Code = "INFANTIL_FOOTBALL",
                            CreatedAt = new DateTime(2025, 9, 28, 16, 31, 21, 586, DateTimeKind.Utc).AddTicks(8501),
                            CreatedBy = "System",
                            IsActive = true,
                            MaxAge = 14,
                            MinAge = 13,
                            Name = "Infantil",
                            SortOrder = 3,
                            Sport = "Football"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111004"),
                            Code = "CADETE_FOOTBALL",
                            CreatedAt = new DateTime(2025, 9, 28, 16, 31, 21, 586, DateTimeKind.Utc).AddTicks(8504),
                            CreatedBy = "System",
                            IsActive = true,
                            MaxAge = 16,
                            MinAge = 15,
                            Name = "Cadete",
                            SortOrder = 4,
                            Sport = "Football"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111005"),
                            Code = "JUVENIL_FOOTBALL",
                            CreatedAt = new DateTime(2025, 9, 28, 16, 31, 21, 586, DateTimeKind.Utc).AddTicks(8506),
                            CreatedBy = "System",
                            IsActive = true,
                            MaxAge = 18,
                            MinAge = 17,
                            Name = "Juvenil",
                            SortOrder = 5,
                            Sport = "Football"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111006"),
                            Code = "JUNIOR_FOOTBALL",
                            CreatedAt = new DateTime(2025, 9, 28, 16, 31, 21, 586, DateTimeKind.Utc).AddTicks(8508),
                            CreatedBy = "System",
                            IsActive = true,
                            MaxAge = 20,
                            MinAge = 19,
                            Name = "Junior",
                            SortOrder = 6,
                            Sport = "Football"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111007"),
                            Code = "SENIOR_FOOTBALL",
                            CreatedAt = new DateTime(2025, 9, 28, 16, 31, 21, 586, DateTimeKind.Utc).AddTicks(8511),
                            CreatedBy = "System",
                            IsActive = true,
                            MaxAge = 34,
                            MinAge = 21,
                            Name = "Senior",
                            SortOrder = 7,
                            Sport = "Football"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111008"),
                            Code = "VETERANO_FOOTBALL",
                            CreatedAt = new DateTime(2025, 9, 28, 16, 31, 21, 586, DateTimeKind.Utc).AddTicks(8513),
                            CreatedBy = "System",
                            IsActive = true,
                            MaxAge = 50,
                            MinAge = 35,
                            Name = "Veterano",
                            SortOrder = 8,
                            Sport = "Football"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222001"),
                            Code = "MINI_BASKETBALL",
                            CreatedAt = new DateTime(2025, 9, 28, 16, 31, 21, 586, DateTimeKind.Utc).AddTicks(8524),
                            CreatedBy = "System",
                            IsActive = true,
                            MaxAge = 10,
                            MinAge = 8,
                            Name = "Mini",
                            SortOrder = 1,
                            Sport = "Basketball"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222002"),
                            Code = "INFANTIL_BASKETBALL",
                            CreatedAt = new DateTime(2025, 9, 28, 16, 31, 21, 586, DateTimeKind.Utc).AddTicks(8527),
                            CreatedBy = "System",
                            IsActive = true,
                            MaxAge = 13,
                            MinAge = 11,
                            Name = "Infantil",
                            SortOrder = 2,
                            Sport = "Basketball"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222003"),
                            Code = "CADETE_BASKETBALL",
                            CreatedAt = new DateTime(2025, 9, 28, 16, 31, 21, 586, DateTimeKind.Utc).AddTicks(8529),
                            CreatedBy = "System",
                            IsActive = true,
                            MaxAge = 16,
                            MinAge = 14,
                            Name = "Cadete",
                            SortOrder = 3,
                            Sport = "Basketball"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222004"),
                            Code = "JUVENIL_BASKETBALL",
                            CreatedAt = new DateTime(2025, 9, 28, 16, 31, 21, 586, DateTimeKind.Utc).AddTicks(8531),
                            CreatedBy = "System",
                            IsActive = true,
                            MaxAge = 18,
                            MinAge = 17,
                            Name = "Juvenil",
                            SortOrder = 4,
                            Sport = "Basketball"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222005"),
                            Code = "SENIOR_BASKETBALL",
                            CreatedAt = new DateTime(2025, 9, 28, 16, 31, 21, 586, DateTimeKind.Utc).AddTicks(8533),
                            CreatedBy = "System",
                            IsActive = true,
                            MaxAge = 40,
                            MinAge = 19,
                            Name = "Senior",
                            SortOrder = 5,
                            Sport = "Basketball"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333001"),
                            Code = "INFANTIL_HANDBALL",
                            CreatedAt = new DateTime(2025, 9, 28, 16, 31, 21, 586, DateTimeKind.Utc).AddTicks(8539),
                            CreatedBy = "System",
                            IsActive = true,
                            MaxAge = 12,
                            MinAge = 10,
                            Name = "Infantil",
                            SortOrder = 1,
                            Sport = "Handball"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333002"),
                            Code = "CADETE_HANDBALL",
                            CreatedAt = new DateTime(2025, 9, 28, 16, 31, 21, 586, DateTimeKind.Utc).AddTicks(8541),
                            CreatedBy = "System",
                            IsActive = true,
                            MaxAge = 15,
                            MinAge = 13,
                            Name = "Cadete",
                            SortOrder = 2,
                            Sport = "Handball"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333003"),
                            Code = "JUVENIL_HANDBALL",
                            CreatedAt = new DateTime(2025, 9, 28, 16, 31, 21, 586, DateTimeKind.Utc).AddTicks(8543),
                            CreatedBy = "System",
                            IsActive = true,
                            MaxAge = 18,
                            MinAge = 16,
                            Name = "Juvenil",
                            SortOrder = 3,
                            Sport = "Handball"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333004"),
                            Code = "SENIOR_HANDBALL",
                            CreatedAt = new DateTime(2025, 9, 28, 16, 31, 21, 586, DateTimeKind.Utc).AddTicks(8546),
                            CreatedBy = "System",
                            IsActive = true,
                            MaxAge = 40,
                            MinAge = 19,
                            Name = "Senior",
                            SortOrder = 4,
                            Sport = "Handball"
                        });
                });

            modelBuilder.Entity("SportPlanner.Domain.Entities.Gender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("genders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "M",
                            CreatedAt = new DateTime(2025, 9, 28, 16, 31, 21, 586, DateTimeKind.Utc).AddTicks(7734),
                            CreatedBy = "System",
                            Description = "Equipos masculinos",
                            IsActive = true,
                            Name = "Masculino"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "F",
                            CreatedAt = new DateTime(2025, 9, 28, 16, 31, 21, 586, DateTimeKind.Utc).AddTicks(7744),
                            CreatedBy = "System",
                            Description = "Equipos femeninos",
                            IsActive = true,
                            Name = "Femenino"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Code = "X",
                            CreatedAt = new DateTime(2025, 9, 28, 16, 31, 21, 586, DateTimeKind.Utc).AddTicks(7748),
                            CreatedBy = "System",
                            Description = "Equipos de género mixto",
                            IsActive = true,
                            Name = "Mixto"
                        });
                });

            modelBuilder.Entity("SportPlanner.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxTeams")
                        .HasColumnType("integer");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("integer");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sport")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("SportPlanner.Domain.Entities.SubscriptionUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GrantedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RemovedBy")
                        .HasColumnType("text");

                    b.Property<int>("RoleInSubscription")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId", "RemovedAt")
                        .HasFilter("removed_at IS NULL");

                    b.HasIndex("SubscriptionId", "UserId")
                        .IsUnique();

                    b.ToTable("SubscriptionUsers");
                });

            modelBuilder.Entity("SportPlanner.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgeGroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowMixedGender")
                        .HasColumnType("boolean");

                    b.Property<string>("CoachName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("CurrentPlayersCount")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("GenderId")
                        .HasColumnType("uuid");

                    b.Property<string>("HomeVenue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastMatchDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("Season")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamCategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("AgeGroupId")
                        .HasDatabaseName("IX_Teams_AgeGroupId");

                    b.HasIndex("GenderId")
                        .HasDatabaseName("IX_Teams_GenderId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Teams_IsActive");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("IX_Teams_SubscriptionId");

                    b.HasIndex("TeamCategoryId")
                        .HasDatabaseName("IX_Teams_TeamCategoryId");

                    b.HasIndex("SubscriptionId", "IsActive")
                        .HasDatabaseName("IX_Teams_SubscriptionId_IsActive");

                    b.HasIndex("SubscriptionId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Teams_SubscriptionId_Name");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("SportPlanner.Domain.Entities.TeamCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("Sport", "SortOrder");

                    b.ToTable("team_categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            Code = "NIVEL_A",
                            CreatedAt = new DateTime(2025, 9, 28, 16, 31, 21, 586, DateTimeKind.Utc).AddTicks(8261),
                            CreatedBy = "System",
                            Description = "Categoría principal - máximo nivel competitivo",
                            IsActive = true,
                            Name = "Nivel A",
                            SortOrder = 1,
                            Sport = "Football"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            Code = "NIVEL_B",
                            CreatedAt = new DateTime(2025, 9, 28, 16, 31, 21, 586, DateTimeKind.Utc).AddTicks(8269),
                            CreatedBy = "System",
                            Description = "Segunda categoría - nivel competitivo medio",
                            IsActive = true,
                            Name = "Nivel B",
                            SortOrder = 2,
                            Sport = "Football"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            Code = "ESCUELA",
                            CreatedAt = new DateTime(2025, 9, 28, 16, 31, 21, 586, DateTimeKind.Utc).AddTicks(8272),
                            CreatedBy = "System",
                            Description = "Categoría de formación y aprendizaje",
                            IsActive = true,
                            Name = "Escuela",
                            SortOrder = 3,
                            Sport = "Football"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            Code = "ELITE",
                            CreatedAt = new DateTime(2025, 9, 28, 16, 31, 21, 586, DateTimeKind.Utc).AddTicks(8276),
                            CreatedBy = "System",
                            Description = "Categoría de élite - máximo rendimiento",
                            IsActive = true,
                            Name = "Elite",
                            SortOrder = 4,
                            Sport = "Football"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222201"),
                            Code = "NIVEL_A_BASKET",
                            CreatedAt = new DateTime(2025, 9, 28, 16, 31, 21, 586, DateTimeKind.Utc).AddTicks(8304),
                            CreatedBy = "System",
                            Description = "Categoría principal - máximo nivel competitivo",
                            IsActive = true,
                            Name = "Nivel A",
                            SortOrder = 1,
                            Sport = "Basketball"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222202"),
                            Code = "NIVEL_B_BASKET",
                            CreatedAt = new DateTime(2025, 9, 28, 16, 31, 21, 586, DateTimeKind.Utc).AddTicks(8371),
                            CreatedBy = "System",
                            Description = "Segunda categoría - nivel competitivo medio",
                            IsActive = true,
                            Name = "Nivel B",
                            SortOrder = 2,
                            Sport = "Basketball"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222203"),
                            Code = "ESCUELA_BASKET",
                            CreatedAt = new DateTime(2025, 9, 28, 16, 31, 21, 586, DateTimeKind.Utc).AddTicks(8373),
                            CreatedBy = "System",
                            Description = "Categoría de formación y aprendizaje",
                            IsActive = true,
                            Name = "Escuela",
                            SortOrder = 3,
                            Sport = "Basketball"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333301"),
                            Code = "NIVEL_A_HANDBALL",
                            CreatedAt = new DateTime(2025, 9, 28, 16, 31, 21, 586, DateTimeKind.Utc).AddTicks(8386),
                            CreatedBy = "System",
                            Description = "Categoría principal - máximo nivel competitivo",
                            IsActive = true,
                            Name = "Nivel A",
                            SortOrder = 1,
                            Sport = "Handball"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333302"),
                            Code = "NIVEL_B_HANDBALL",
                            CreatedAt = new DateTime(2025, 9, 28, 16, 31, 21, 586, DateTimeKind.Utc).AddTicks(8389),
                            CreatedBy = "System",
                            Description = "Segunda categoría - nivel competitivo medio",
                            IsActive = true,
                            Name = "Nivel B",
                            SortOrder = 2,
                            Sport = "Handball"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333303"),
                            Code = "ESCUELA_HANDBALL",
                            CreatedAt = new DateTime(2025, 9, 28, 16, 31, 21, 586, DateTimeKind.Utc).AddTicks(8392),
                            CreatedBy = "System",
                            Description = "Categoría de formación y aprendizaje",
                            IsActive = true,
                            Name = "Escuela",
                            SortOrder = 3,
                            Sport = "Handball"
                        });
                });

            modelBuilder.Entity("SportPlanner.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SportPlanner.Domain.Entities.SubscriptionUser", b =>
                {
                    b.HasOne("SportPlanner.Domain.Entities.Subscription", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SportPlanner.Domain.Entities.Team", b =>
                {
                    b.HasOne("SportPlanner.Domain.Entities.AgeGroup", "AgeGroup")
                        .WithMany()
                        .HasForeignKey("AgeGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportPlanner.Domain.Entities.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportPlanner.Domain.Entities.Subscription", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportPlanner.Domain.Entities.TeamCategory", "Category")
                        .WithMany()
                        .HasForeignKey("TeamCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgeGroup");

                    b.Navigation("Category");

                    b.Navigation("Gender");
                });
#pragma warning restore 612, 618
        }
    }
}
